#!/usr/bin/env python3
"""Build bounded PPO replay and cross-generation elite archives for STS1 PPO v1.4.

Safety model:
- Fresh rollout data is always the primary PPO dataset.
- PPO replay accepts only episodes generated by the exact same Training Parent
  checkpoint. Replay episodes preserve their own behavior temperature/log-prob.
- Cross-generation elite data is never used in PPO ratios; it is exported only
  for low-weight self-imitation/BC.
- Replay operates on complete games so GAE episode boundaries are preserved.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np


SCHEMA = "sts1-armg-ppo-v14-replay-v1"


def _checkpoint_id(d: Any) -> str:
    values = list(map(str, np.asarray(d["checkpoint_id"]).reshape(-1)))
    if not values:
        raise RuntimeError("missing checkpoint_id")
    return values[0]


def _split_games(
    path: Path,
    *,
    source_round: int | None = None,
) -> list[dict[str, Any]]:
    with np.load(path, allow_pickle=False) as d:
        checkpoint = _checkpoint_id(d)
        seeds = np.asarray(d["game_seed"], np.int64)
        obs = np.asarray(d["obs"], np.float32)
        desc = np.asarray(d["desc"], np.float32)
        offsets = np.asarray(d["offsets"], np.int64)
        counts = np.asarray(d["counts"], np.int32)
        action = np.asarray(d["action"], np.int64)
        reward = np.asarray(d["reward"], np.float32)
        old_logp = np.asarray(d["old_logp"], np.float32)
        done = np.asarray(d["done"], np.bool_)

        n = len(action)
        if not (
            len(seeds)
            == len(obs)
            == len(counts)
            == len(reward)
            == len(old_logp)
            == len(done)
            == n
        ):
            raise RuntimeError(f"row length mismatch in {path}")
        if len(offsets) != n + 1 or int(offsets[-1]) != len(desc):
            raise RuntimeError(f"packed candidate offsets invalid in {path}")

        temperatures = (
            np.asarray(d["behavior_temperature"], np.float32)
            if "behavior_temperature" in d
            else np.ones(n, np.float32)
        )
        victories = (
            np.asarray(d["game_victory"], np.bool_)
            if "game_victory" in d
            else np.zeros(n, np.bool_)
        )
        floors = (
            np.asarray(d["game_final_floor"], np.int16)
            if "game_final_floor" in d
            else np.zeros(n, np.int16)
        )
        rounds = (
            np.asarray(d["source_round"], np.int32)
            if "source_round" in d
            else np.zeros(n, np.int32)
        )
        source_checkpoints = (
            np.asarray(d["source_checkpoint_id"]).astype(str)
            if "source_checkpoint_id" in d
            else np.asarray([checkpoint] * n)
        )

        if not (
            len(temperatures)
            == len(victories)
            == len(floors)
            == len(rounds)
            == len(source_checkpoints)
            == n
        ):
            raise RuntimeError(f"metadata length mismatch in {path}")

        games: list[dict[str, Any]] = []
        for seed in sorted(set(map(int, seeds))):
            idx = np.flatnonzero(seeds == seed)
            if len(idx) == 0:
                continue
            if int(done[idx].sum()) != 1 or not bool(done[idx[-1]]):
                raise RuntimeError(f"game {seed} has invalid terminal boundary in {path}")
            if not np.all(source_checkpoints[idx] == source_checkpoints[idx[0]]):
                raise RuntimeError(f"game {seed} checkpoint identity drift")
            if not np.allclose(temperatures[idx], temperatures[idx[0]], atol=1e-7):
                raise RuntimeError(f"game {seed} behavior temperature drift")
            if not np.all(victories[idx] == victories[idx[0]]):
                raise RuntimeError(f"game {seed} victory metadata drift")
            if not np.all(floors[idx] == floors[idx[0]]):
                raise RuntimeError(f"game {seed} floor metadata drift")

            desc_parts = [
                desc[offsets[i] : offsets[i + 1]]
                for i in idx
            ]
            game_round = int(rounds[idx[0]])
            if source_round is not None:
                game_round = int(source_round)
            games.append(
                {
                    "seed": int(seed),
                    "checkpoint_id": str(source_checkpoints[idx[0]]),
                    "source_round": game_round,
                    "temperature": float(temperatures[idx[0]]),
                    "victory": bool(victories[idx[0]]),
                    "final_floor": int(floors[idx[0]]),
                    "obs": obs[idx].copy(),
                    "desc_parts": [part.copy() for part in desc_parts],
                    "action": action[idx].copy(),
                    "reward": reward[idx].copy(),
                    "old_logp": old_logp[idx].copy(),
                    "done": done[idx].copy(),
                }
            )
        return games


def _load_directory(directory: Path, *, source_round: int) -> list[dict[str, Any]]:
    files = sorted(directory.glob("shard_*.npz"))
    if not files:
        raise RuntimeError(f"no fresh shards in {directory}")
    games: list[dict[str, Any]] = []
    for path in files:
        games.extend(_split_games(path, source_round=source_round))
    return games


def _load_optional(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        return []
    return _split_games(path)


def _dedupe(
    games: list[dict[str, Any]],
    *,
    key_with_checkpoint: bool,
) -> list[dict[str, Any]]:
    selected: dict[Any, dict[str, Any]] = {}
    for game in games:
        key: Any = int(game["seed"])
        if key_with_checkpoint:
            key = (str(game["checkpoint_id"]), int(game["seed"]))
        previous = selected.get(key)
        if previous is None or int(game["source_round"]) >= int(previous["source_round"]):
            selected[key] = game
    return list(selected.values())


def _pack(path: Path, games: list[dict[str, Any]], *, checkpoint_id: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not games:
        if path.exists():
            path.unlink()
        return

    obs_parts = []
    desc_parts = []
    action_parts = []
    reward_parts = []
    old_logp_parts = []
    done_parts = []
    seed_parts = []
    temp_parts = []
    victory_parts = []
    floor_parts = []
    round_parts = []
    checkpoint_parts = []
    counts_parts = []

    for game in games:
        n = len(game["action"])
        if n == 0:
            continue
        obs_parts.append(np.asarray(game["obs"], np.float32))
        action_parts.append(np.asarray(game["action"], np.int64))
        reward_parts.append(np.asarray(game["reward"], np.float32))
        old_logp_parts.append(np.asarray(game["old_logp"], np.float32))
        done_parts.append(np.asarray(game["done"], np.bool_))
        seed_parts.append(np.full(n, int(game["seed"]), np.int64))
        temp_parts.append(np.full(n, float(game["temperature"]), np.float32))
        victory_parts.append(np.full(n, bool(game["victory"]), np.bool_))
        floor_parts.append(np.full(n, int(game["final_floor"]), np.int16))
        round_parts.append(np.full(n, int(game["source_round"]), np.int32))
        checkpoint_parts.append(
            np.asarray([str(game["checkpoint_id"])] * n)
        )
        local_counts = np.asarray(
            [len(x) for x in game["desc_parts"]],
            np.int32,
        )
        counts_parts.append(local_counts)
        desc_parts.extend(
            np.asarray(x, np.float32)
            for x in game["desc_parts"]
        )

    obs = np.concatenate(obs_parts, axis=0)
    action = np.concatenate(action_parts)
    reward = np.concatenate(reward_parts)
    old_logp = np.concatenate(old_logp_parts)
    done = np.concatenate(done_parts)
    game_seed = np.concatenate(seed_parts)
    behavior_temperature = np.concatenate(temp_parts)
    game_victory = np.concatenate(victory_parts)
    game_final_floor = np.concatenate(floor_parts)
    source_round = np.concatenate(round_parts)
    source_checkpoint_id = np.concatenate(checkpoint_parts)
    counts = np.concatenate(counts_parts)
    offsets = np.zeros(len(counts) + 1, np.int64)
    np.cumsum(counts, out=offsets[1:])
    desc = np.concatenate(desc_parts, axis=0)

    if int(offsets[-1]) != len(desc):
        raise RuntimeError("packed replay candidate mismatch")

    np.savez_compressed(
        path,
        obs=obs,
        desc=desc,
        offsets=offsets,
        counts=counts,
        action=action,
        reward=reward,
        old_logp=old_logp,
        done=done,
        game_seed=game_seed,
        behavior_temperature=behavior_temperature,
        game_victory=game_victory,
        game_final_floor=game_final_floor,
        source_round=source_round,
        source_checkpoint_id=source_checkpoint_id,
        checkpoint_id=np.asarray([checkpoint_id]),
    )


def _game_decisions(games: list[dict[str, Any]]) -> int:
    return int(sum(len(game["action"]) for game in games))


def _recent_key(game: dict[str, Any]) -> tuple[int, int]:
    return (int(game["source_round"]), int(game["seed"]))


def _winner_replay_key(game: dict[str, Any]) -> tuple[int, int, int, int]:
    """Prefer proven wins, then deeper failures, without duplicating episodes."""
    return (
        int(bool(game["victory"])),
        int(game["final_floor"]),
        int(game["source_round"]),
        int(game["seed"]),
    )


def _elite_key(game: dict[str, Any]) -> tuple[int, int, int, int]:
    return (
        int(bool(game["victory"])),
        int(game["final_floor"]),
        int(game["source_round"]),
        int(game["seed"]),
    )


def _select_rescue_replay(
    games: list[dict[str, Any]],
    *,
    max_games: int,
    decision_budget: int,
) -> list[dict[str, Any]]:
    """Mix wins, deep losses, and recent episodes without duplicating games."""
    if max_games <= 0 or decision_budget <= 0 or not games:
        return []

    winners = sorted(
        (game for game in games if bool(game["victory"])),
        key=_winner_replay_key,
        reverse=True,
    )
    losses = [game for game in games if not bool(game["victory"])]
    deep_losses = sorted(
        losses,
        key=lambda game: (
            int(game["final_floor"]),
            int(game["source_round"]),
            int(game["seed"]),
        ),
        reverse=True,
    )
    recent_losses = sorted(losses, key=_recent_key, reverse=True)

    win_quota = (max_games + 1) // 2
    deep_quota = (max_games * 3) // 10
    recent_quota = max_games - win_quota - deep_quota

    selected: list[dict[str, Any]] = []
    seen: set[tuple[str, int]] = set()
    used_decisions = 0

    def add_group(group: list[dict[str, Any]], quota: int) -> None:
        nonlocal used_decisions
        added = 0
        for game in group:
            if added >= quota or len(selected) >= max_games:
                break
            key = (str(game["checkpoint_id"]), int(game["seed"]))
            if key in seen:
                continue
            game_decisions = len(game["action"])
            if used_decisions + game_decisions > decision_budget:
                continue
            selected.append(game)
            seen.add(key)
            used_decisions += game_decisions
            added += 1

    add_group(winners, win_quota)
    add_group(deep_losses, deep_quota)
    add_group(recent_losses, recent_quota)

    # If one bucket is undersupplied, use the remaining budget instead of
    # throwing useful data away. Wins stay first, then deepest losses, then recency.
    fallback = winners + deep_losses + recent_losses
    for game in fallback:
        if len(selected) >= max_games:
            break
        key = (str(game["checkpoint_id"]), int(game["seed"]))
        if key in seen:
            continue
        game_decisions = len(game["action"])
        if used_decisions + game_decisions > decision_budget:
            continue
        selected.append(game)
        seen.add(key)
        used_decisions += game_decisions

    return selected


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--fresh-dir", type=Path, required=True)
    p.add_argument("--state-dir", type=Path, required=True)
    p.add_argument("--output-dir", type=Path, required=True)
    p.add_argument("--checkpoint-id", required=True)
    p.add_argument("--round-index", type=int, required=True)
    p.add_argument("--max-ppo-games", type=int, default=1600)
    p.add_argument("--replay-fraction", type=float, default=0.50)
    p.add_argument("--max-elite-games", type=int, default=600)
    p.add_argument("--elite-min-floor", type=int, default=45)
    args = p.parse_args()

    if not 0.0 <= args.replay_fraction <= 0.50:
        raise RuntimeError("replay-fraction must be within 0..0.50")
    if args.max_ppo_games < 1 or args.max_elite_games < 1:
        raise RuntimeError("replay capacities must be positive")

    args.state_dir.mkdir(parents=True, exist_ok=True)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    fresh = _dedupe(
        _load_directory(args.fresh_dir, source_round=args.round_index),
        key_with_checkpoint=False,
    )
    if any(game["checkpoint_id"] != args.checkpoint_id for game in fresh):
        raise RuntimeError("fresh checkpoint identity mismatch")

    ppo_path = args.state_dir / "ppo-replay.npz"
    old_ppo = _load_optional(ppo_path)
    stale_games = sum(
        1
        for game in old_ppo
        if game["checkpoint_id"] != args.checkpoint_id
    )
    same_parent = [
        game
        for game in old_ppo
        if game["checkpoint_id"] == args.checkpoint_id
    ]
    fresh_seeds = {int(game["seed"]) for game in fresh}
    reusable = [
        game
        for game in same_parent
        if int(game["seed"]) not in fresh_seeds
    ]
    train_replay_game_limit = min(
        len(reusable),
        int(len(fresh) * args.replay_fraction),
    )
    replay_decision_budget = int(
        _game_decisions(fresh) * args.replay_fraction
    )
    train_replay = _select_rescue_replay(
        reusable,
        max_games=train_replay_game_limit,
        decision_budget=replay_decision_budget,
    )
    _pack(
        args.output_dir / "replay_00.npz",
        train_replay,
        checkpoint_id=args.checkpoint_id,
    )

    ppo_pool = _dedupe(
        reusable + fresh,
        key_with_checkpoint=False,
    )
    ppo_pool = sorted(ppo_pool, key=_recent_key, reverse=True)[
        : args.max_ppo_games
    ]
    _pack(
        ppo_path,
        ppo_pool,
        checkpoint_id=args.checkpoint_id,
    )

    elite_path = args.state_dir / "elite-replay.npz"
    old_elite = _load_optional(elite_path)
    elite_fresh = [
        game
        for game in fresh
        if bool(game["victory"])
        or int(game["final_floor"]) >= args.elite_min_floor
    ]
    elite_pool = _dedupe(
        old_elite + elite_fresh,
        key_with_checkpoint=True,
    )
    elite_pool = sorted(
        elite_pool,
        key=_elite_key,
        reverse=True,
    )[: args.max_elite_games]
    _pack(
        elite_path,
        elite_pool,
        checkpoint_id="MIXED",
    )

    manifest = {
        "schema_version": SCHEMA,
        "checkpoint_id": args.checkpoint_id,
        "round_index": args.round_index,
        "fresh_games": len(fresh),
        "fresh_decisions": _game_decisions(fresh),
        "train_replay_games": len(train_replay),
        "train_replay_decisions": _game_decisions(train_replay),
        "train_replay_victories": sum(bool(game["victory"]) for game in train_replay),
        "train_replay_selection": "quota_50pct_wins_30pct_deep_losses_20pct_recent_then_fill",
        "train_replay_fraction_of_fresh_games": (
            len(train_replay) / max(1, len(fresh))
        ),
        "train_replay_fraction_of_fresh_decisions": (
            _game_decisions(train_replay)
            / max(1, _game_decisions(fresh))
        ),
        "ppo_pool_games": len(ppo_pool),
        "ppo_pool_decisions": _game_decisions(ppo_pool),
        "stale_ppo_games_rejected": stale_games,
        "elite_fresh_games": len(elite_fresh),
        "elite_pool_games": len(elite_pool),
        "elite_pool_decisions": _game_decisions(elite_pool),
        "elite_victories": sum(bool(x["victory"]) for x in elite_pool),
        "elite_min_floor": args.elite_min_floor,
        "max_ppo_games": args.max_ppo_games,
        "max_elite_games": args.max_elite_games,
    }
    (args.output_dir / "replay-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    state_path = args.state_dir / "state.json"
    if state_path.is_file():
        state = json.loads(state_path.read_text(encoding="utf-8"))
        state["replay_stats"] = manifest
        state_path.write_text(
            json.dumps(state, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    print(
        "PPO_V14_REPLAY_PASS",
        json.dumps(manifest, sort_keys=True),
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
