"""STS1 Phase 2A dataset and behavior-cloning infrastructure."""

from .bc import BCExample, HoldoutAccessError, load_bc_examples
from .dataset import (
    ACTION_SCHEMA_VERSION,
    DATASET_SCHEMA_VERSION,
    PUBLIC_STATE_SCHEMA_VERSION,
    RECORD_SCHEMA_VERSION,
    SPLIT_SCHEMA_VERSION,
    DatasetBuildConfig,
    DuplicateDecisionConflictError,
    POLICY_OBSERVATION_FIELDS,
    ProducerProvenance,
    STS1DatasetError,
    StaleWorkerError,
    build_dataset,
    canonical_json,
    decision_signature_for_policy_input,
    decision_signature_for_public_state,
    legal_action_ids_for_public_state,
    load_manifest,
    make_decision_record,
    project_policy_observation,
    sha256_json,
    split_for_seed,
    validate_decision_record,
)
from .masking import build_legal_action_mask, masked_argmax
from .teacher_capture import (
    FORMAL_CAPTURE_CONFIG,
    FORMAL_SEARCH_CONFIG,
    FORMAL_SIMULATOR_SHA,
    FORMAL_TEACHER_CONFIG_HASH,
    FORMAL_TEACHER_REPOSITORY,
    FORMAL_TEACHER_SHA,
    TIE_SELECTION_POLICY,
    TeacherCaptureError,
    capture_frozen_search_record,
    formal_teacher_provenance,
)

__all__ = [
    "ACTION_SCHEMA_VERSION",
    "BCExample",
    "DATASET_SCHEMA_VERSION",
    "DatasetBuildConfig",
    "DuplicateDecisionConflictError",
    "HoldoutAccessError",
    "FORMAL_CAPTURE_CONFIG",
    "FORMAL_SEARCH_CONFIG",
    "FORMAL_SIMULATOR_SHA",
    "FORMAL_TEACHER_CONFIG_HASH",
    "FORMAL_TEACHER_REPOSITORY",
    "FORMAL_TEACHER_SHA",
    "POLICY_OBSERVATION_FIELDS",
    "ProducerProvenance",
    "PUBLIC_STATE_SCHEMA_VERSION",
    "RECORD_SCHEMA_VERSION",
    "SPLIT_SCHEMA_VERSION",
    "STS1DatasetError",
    "StaleWorkerError",
    "TIE_SELECTION_POLICY",
    "TeacherCaptureError",
    "build_dataset",
    "build_legal_action_mask",
    "canonical_json",
    "capture_frozen_search_record",
    "decision_signature_for_policy_input",
    "decision_signature_for_public_state",
    "legal_action_ids_for_public_state",
    "load_bc_examples",
    "formal_teacher_provenance",
    "load_manifest",
    "make_decision_record",
    "masked_argmax",
    "project_policy_observation",
    "sha256_json",
    "split_for_seed",
    "validate_decision_record",
]
